### ISSUE TITLE
How do i fix this ?

### ISSUE THREAD

**Issue by efsane14010** [dekrypted/discord-image-logger#39]
[GET] /api/main
20:15:47:65
[ERROR] MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./api/main.py", line 120, in <module>
    "normal": requests.get(config["image"]).content,
  File "/var/task/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/var/task/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/task/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/var/task/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/var/task/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/var/task/requests/models.py", line 439, in prepare_url
    raise MissingSchema(START RequestId: e30f62d8-4825-47fd-bde7-999a0bd06419 Version: $LATEST
Unknown application error occurred
Runtime.Unknown

When i try vercel it shows this error in _logs
Also gives this error (photo)
![A33B591F-E868-4CCA-A801-88BDBDFE1A9F](https://user-images.githubusercontent.com/97107742/219115310-18039cee-9aaa-462b-a28c-e9f86bd0213a.png)

**Comment by dekrypted** [comment]
it seems you didn't provide a valid url.

in the image value, you need to provide a **web address** (not a file path) which begins with http:// or https://

e.g https://ih1.redbubble.net/image.1608685554.9678/poster,840x830,f8f8f8-pad,1000x1000,f8f8f8.jpg

**Comment by dekrypted** [comment]
Closed due to inactivity
