### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Dino-log** [dekrypted/discord-image-logger#46]
![image](https://user-images.githubusercontent.com/66836260/221382478-73748853-d9a7-4bc6-be75-64ff5ffec62f.png)

**Comment by Dino-log** [comment]
i did everything like it said in the setup

**Comment by Dino-log** [comment]
it says this on the vercel website


```
[GET] /api/main.py
23:31:28:97
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 45770)
Traceback (most recent call last):
File "/var/lang/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
self.process_request(request, client_address)
File "/var/lang/lib/python3.9/socketserver.py", line 347, in process_request
self.finish_request(request, client_address)
File "/var/lang/lib/python3.9/socketserver.py", line 360, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/var/lang/lib/python3.9/socketserver.py", line 747, in init
self.handle()
File "/var/lang/lib/python3.9/http/server.py", line 425, in handle
self.handle_one_request()
File "/var/lang/lib/python3.9/http/server.py", line 413, in handle_one_request
method()
File "./api/main.py", line 183, in do_GET
if self.headers.get('x-forwarded-for').startswith(blacklistedIPs):
TypeError: tuple for startswith must only contain str, not tuple
----------------------------------------
[ERROR] RemoteDisconnected: Remote end closed connection without response
Traceback (most recent call last):
  File "/var/task/vchandlerpython.py", line 66, in vc_handler
    res = conn.getresponse()
  File "/var/lang/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/var/lang/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/var/lang/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
```

**Comment by dekrypted** [comment]
oh hey, you found a bug!
thank you. i didnt even notice this. it's fixed in the latest version :)
